# Generated by Django 4.2.7 on 2024-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='descrpiction',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Welcome to our platform! Please share your thoughts and experiences here.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
